package lexical

const (
	IF = "if"
	ELSE = "else"
	OPEN_PARENTHESE = "("
	CLOSE_PARENTHESE = ")"
	EQUALITY = "=="
	INEQUALITY = "!="
	LESS = "<"
	EQUAL_LESS = "<="
	GREAT = ">"
	EQUAL_GREAT = ">="
	NOT = "!"
	OPEN_BRACE = "{"
	CLOSE_BRACE = "}"
	BREAK_LINE = "\n"
	AND = "&&"
	OR = "||"
	IDENTIFIER = "[a-zA-Z]\\w*"
	ATTRIBUTE = "^[a-zA-Z]\\w*"
	INT_VALUE = "[0-9]+"
	FLOAT_VALUE = "[0-9]+.[0-9+]"
	STRING_VALUE = "\"[a-zA-Z]\\w*\""
)